name: Build Publish Main
on:
  push:
    branches:
      - main
      - $default-branch
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Build and Release
        run: pnpm run release:main
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
